development:
  adapter: postgresql
  encoding: unicode
  database: dev_pledge_development
  pool: 5
  username: tomas
  password: YOUR_PASSWORD

test:
  adapter: postgresql
  encoding: unicode
  database: dev_pledge_test
  pool: 5
  username: tomas
  password: YOUR_PASSWORD
