development:
  adapter: postgresql
  encoding: unicode
  database: code_monkey_development
  pool: 5
  username: tomas
  password: YOUR_PASSWORD

test:
  adapter: postgresql
  encoding: unicode
  database: code_monkey_test
  pool: 5
  username: tomas
  password: YOUR_PASSWORD
