development:
  adapter: postgresql
  encoding: unicode
  database: dev_pledge_development
  pool: 5
  username: <%= ENV['YOUR_USERNAME'] %>
  password: YOUR_PASSWORD

test:
  adapter: postgresql
  encoding: unicode
  database: dev_pledge_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: <%= ENV['YOUR_USERNAME'] %>
  password: YOUR_PASSWORD
