# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc1c006a6545b87c143c2276cb567cccb7b62837c24b00d169939fcea0222ff774d72ae466f25328d6187164835654703184a74b50cf4a98c4a98d0a236a2432

test:
  secret_key_base: d88f9b19b4a237e172abc1bfe84f231898b9420389934085d96b7d2ee10b1a12d530a68719a8db52fe8cd38f61fc72025ffbafab38a05dcdd9cedd1a08117be9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
